version: '3'

services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data:Z
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: unless-stopped

  app:
    image: nextcloud:apache
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html:z
    environment:
      - VIRTUAL_HOST=cloud.performans.com
      - LETSENCRYPT_HOST=cloud.performans.com
      - LETSENCRYPT_EMAIL=admin@performans.com
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
      - SMTP_HOST=mail.domain.com
      - SMTP_PORT=587
      - SMTP_NAME=user@domain.com
      - SMTP_PASSWORD=password
      - MAIL_FROM_ADDRESS=cloud@domain.com
    env_file:
      - db.env
    depends_on:
      - db
      - redis
    networks:
      - proxy-tier
      - default

  cron:
    image: nextcloud:apache
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html:z
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  proxy:
    build: ./proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:z,ro
      - vhost.d:/etc/nginx/vhost.d:z
      - html:/usr/share/nginx/html:z
      - /var/run/docker.sock:/tmp/docker.sock:z,ro
    networks:
      - proxy-tier

  # letsencrypt-companion:
  #   image: nginxproxy/acme-companion
  #   restart: unless-stopped
  #   volumes:
  #     - certs:/etc/nginx/certs:z
  #     - acme:/etc/acme.sh:z
  #     - vhost.d:/etc/nginx/vhost.d:z
  #     - html:/usr/share/nginx/html:z
  #     - /var/run/docker.sock:/var/run/docker.sock:z,ro
  #   networks:
  #     - proxy-tier
  #   depends_on:
  #     - proxy

  # self signed
  omgwtfssl:
    image: paulczar/omgwtfssl
    restart: "no"
    volumes:
      - certs:/certs
    environment:
      - SSL_SUBJECT=cloud.performans.com
      - CA_SUBJECT=admin@performans.com
      - SSL_KEY=/certs/cloud.performans.com.key
      - SSL_CSR=/certs/cloud.performans.com.csr
      - SSL_CERT=/certs/cloud.performans.com.crt
    networks:
      - proxy-tier

volumes:
  db:
  nextcloud:
  certs:
  acme:
  vhost.d:
  html:

networks:
  proxy-tier:
